# Generated by Django 5.1.4 on 2025-02-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='expiration_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
